import enum
from datetime import date, datetime
from decimal import Decimal
from typing import Optional

from sqlalchemy import (
    Boolean,
    Date,
    DateTime,
    Enum,
    ForeignKey,
    Integer,
    Numeric,
    String,
    event,
    func,
)
from sqlalchemy.orm import Mapped, Mapper, mapped_column, relationship

from app.models.base import Base


class TransactionType(str, enum.Enum):
    INCOME = "income"
    EXPENSE = "expense"
    TRANSFER = "transfer"


class TransactionStatus(str, enum.Enum):
    SETTLED = "settled"
    PENDING = "pending"


class Transaction(Base):
    """Financial transaction.

    Transfers between own accounts are modeled as TWO paired rows (one
    EXPENSE on the source account, one INCOME on the destination), linked
    bidirectionally via ``linked_transaction_id`` (self-FK, ondelete=SET NULL).

    Transfer-pair invariants (enforced by the pairing service):
      1. Both rows belong to the same org.
      2. Linked bidirectionally.
      3. Opposite types (EXPENSE / INCOME).
      4. Equal absolute amounts.
      5. Different accounts.
      6. Same currency, evaluated as A.account.currency == B.account.currency.
      7. Neither row may already be linked to a third row before pairing.
      8. The reserved TransactionType.TRANSFER value is not used by the
         pairing model; legs are typed by direction.

    ``linked_transaction_id`` is **created** only by
    ``transaction_service._link_pair`` and **cleared** only by
    ``transaction_service.unpair_transactions``. Other code paths must not
    write this column directly.

    Reporting semantics: income/expense aggregates treat rows with
    ``linked_transaction_id IS NULL`` as reportable. Use
    ``app.services.transaction_filters.reportable_transaction_filter()``
    in queries and ``is_reportable_transaction(tx)`` / ``is_transfer_leg(tx)``
    in Python predicates.
    """

    __tablename__ = "transactions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    org_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("organizations.id"), nullable=False
    )
    account_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("accounts.id"), nullable=False
    )
    category_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("categories.id"), nullable=False
    )
    description: Mapped[str] = mapped_column(String(255), nullable=False)
    amount: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False)
    type: Mapped[TransactionType] = mapped_column(
        Enum(TransactionType, values_callable=lambda x: [e.value for e in x]),
        nullable=False,
    )
    status: Mapped[TransactionStatus] = mapped_column(
        Enum(TransactionStatus, values_callable=lambda x: [e.value for e in x]),
        nullable=False,
        default=TransactionStatus.SETTLED,
    )
    linked_transaction_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("transactions.id", ondelete="SET NULL"), nullable=True
    )
    recurring_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("recurring_transactions.id", ondelete="SET NULL"), nullable=True
    )
    date: Mapped[date] = mapped_column(Date, nullable=False)
    settled_date: Mapped[Optional[date]] = mapped_column(Date, nullable=True)
    is_imported: Mapped[bool] = mapped_column(Boolean, default=False, server_default="0", nullable=False)
    # Track E: True only for rows generated by adjust_account_balance.
    # Flagged so reportable_transaction_filter() excludes them from
    # income/expense aggregates, transfer-pair detection ignores them,
    # and standard CRUD (update/delete/promote_to_recurring) refuses to
    # touch them. reconcile_account intentionally still counts these
    # rows so the stored-balance invariant holds.
    is_manual_adjustment: Mapped[bool] = mapped_column(
        Boolean, default=False, server_default="0", nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), onupdate=func.now(), nullable=False
    )

    account: Mapped["Account"] = relationship()
    category: Mapped["Category"] = relationship(back_populates="transactions")
    linked_transaction: Mapped[Optional["Transaction"]] = relationship(
        foreign_keys=[linked_transaction_id], remote_side="Transaction.id"
    )
    # PR-Tags-A: many-to-many to Tag through transaction_tags. Service
    # callers eager-load via selectinload(Transaction.tags) on list /
    # get queries; without that, accessing .tags on a detached
    # transaction raises MissingGreenlet. The TransactionTag join
    # ON DELETE CASCADE handles cleanup on either side.
    tags: Mapped[list["Tag"]] = relationship(
        secondary="transaction_tags",
        order_by="Tag.name_normalized",
        viewonly=True,
    )


def _enforce_settled_implies_settled_date(_mapper: Mapper, _conn, target: Transaction) -> None:
    """SETTLED-implies-settled_date invariant guard at flush time.

    Mirrors the DB CHECK constraint added in migration 036, but raises
    a clear ValueError before the row hits the database so callers see
    a typed Python error instead of an opaque IntegrityError. Runs at
    flush time (not on attribute assignment) so the check sees the
    final, post-construction state of both columns and is independent
    of kwarg ordering in ``Transaction(...)`` constructors.
    """
    if target.status == TransactionStatus.SETTLED and target.settled_date is None:
        raise ValueError(
            "Transaction with status=SETTLED must have a settled_date "
            "(SETTLED-implies-settled_date invariant)."
        )


event.listen(Transaction, "before_insert", _enforce_settled_implies_settled_date)
event.listen(Transaction, "before_update", _enforce_settled_implies_settled_date)
