"""Manual balance adjustment (Track E).

Revision ID: 035_manual_balance_adjustment
Revises: 034_unique_org_name
Create Date: 2026-05-08

Three additive changes:

1. ``organizations.allow_manual_balance_adjustment`` boolean (default 0).
   Org admins toggle this on to allow direct balance edits on accounts.
   Default OFF preserves the historical invariant that ``account.balance``
   is derived strictly from transactions.

2. ``transactions.is_manual_adjustment`` boolean (default 0). Marks the
   tx rows generated by the new ``POST /accounts/{id}/adjust-balance``
   endpoint so reporting filters can exclude them, transfer detection
   can ignore them, and bulk delete can skip them.

3. ``UNIQUE(org_id, slug, is_system)`` on ``categories``. The new lazy
   ``balance-adjustment`` system category is created on first use under
   a try/except IntegrityError race; the unique index is what makes
   that race-safe. Defensive precheck scans for any existing
   ``(org_id, slug, is_system)`` duplicates before adding the index so
   a polluted dataset bails with a clear error rather than crashing on
   the DDL.
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = "035_manual_balance_adjustment"
down_revision = "034_unique_org_name"
branch_labels = None
depends_on = None


def _check_no_category_duplicates(bind) -> None:
    rows = bind.execute(
        sa.text(
            "SELECT org_id, slug, is_system, COUNT(*) AS n "
            "FROM categories "
            "WHERE slug IS NOT NULL "
            "GROUP BY org_id, slug, is_system "
            "HAVING COUNT(*) > 1"
        )
    ).all()
    if rows:
        rendered = ", ".join(
            f"(org={r.org_id}, slug={r.slug!r}, is_system={r.is_system}, x{r.n})"
            for r in rows
        )
        raise RuntimeError(
            "Cannot create UNIQUE(org_id, slug, is_system) on categories: "
            f"duplicates exist: {rendered}. Resolve them and re-run."
        )


def upgrade() -> None:
    bind = op.get_bind()

    # 1. organizations.allow_manual_balance_adjustment
    op.add_column(
        "organizations",
        sa.Column(
            "allow_manual_balance_adjustment",
            sa.Boolean(),
            nullable=False,
            server_default="0",
        ),
    )

    # 2. transactions.is_manual_adjustment
    op.add_column(
        "transactions",
        sa.Column(
            "is_manual_adjustment",
            sa.Boolean(),
            nullable=False,
            server_default="0",
        ),
    )

    # 3. UNIQUE(org_id, slug, is_system) on categories
    _check_no_category_duplicates(bind)
    if bind.dialect.name == "mysql":
        op.create_unique_constraint(
            "uq_categories_org_slug_system",
            "categories",
            ["org_id", "slug", "is_system"],
        )
    else:
        # SQLite (test) dialect: plain UNIQUE INDEX.
        op.create_index(
            "uq_categories_org_slug_system",
            "categories",
            ["org_id", "slug", "is_system"],
            unique=True,
        )


def downgrade() -> None:
    bind = op.get_bind()

    if bind.dialect.name == "mysql":
        op.drop_constraint(
            "uq_categories_org_slug_system",
            "categories",
            type_="unique",
        )
    else:
        op.drop_index(
            "uq_categories_org_slug_system",
            table_name="categories",
        )

    op.drop_column("transactions", "is_manual_adjustment")
    op.drop_column("organizations", "allow_manual_balance_adjustment")
