import datetime
from decimal import Decimal
from typing import Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


class TransactionCreate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    account_id: int
    category_id: int
    description: str = Field(max_length=255)
    amount: Decimal = Field(gt=0, max_digits=12, decimal_places=2)
    type: Literal["income", "expense"]
    status: Literal["settled", "pending"] = "settled"
    date: datetime.date
    # Optional expected settlement date for pending rows. When status=pending
    # and the user provides this, it surfaces in the period bucket
    # (effective_period_date_expr) so forecasts and period filters see the
    # row in its expected month rather than its purchase month. Stored
    # as-is for SETTLED rows when explicitly supplied; the service layer
    # falls back to the transaction date if omitted on SETTLED creates so
    # the SETTLED-implies-settled_date invariant holds.
    settled_date: Optional[datetime.date] = None

    @field_validator("description")
    @classmethod
    def description_not_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Description is required")
        return v.strip()

    @model_validator(mode="after")
    def _settled_date_not_before_date(self) -> "TransactionCreate":
        if self.settled_date is not None and self.settled_date < self.date:
            raise ValueError("settled_date must be on or after date")
        return self


class TransferCreate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    from_account_id: int
    to_account_id: int
    category_id: Optional[int] = None
    description: str = Field(default="", max_length=255)
    amount: Decimal = Field(gt=0, max_digits=12, decimal_places=2)
    status: Literal["settled", "pending"] = "settled"
    date: datetime.date


class TransactionUpdate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    account_id: Optional[int] = None
    category_id: Optional[int] = None
    description: Optional[str] = None
    amount: Optional[Decimal] = Field(default=None, gt=0, max_digits=12, decimal_places=2)
    type: Optional[Literal["income", "expense"]] = None
    status: Optional[Literal["settled", "pending"]] = None
    settled_date: Optional[datetime.date] = None
    date: Optional[datetime.date] = None

    @field_validator("description")
    @classmethod
    def description_not_empty(cls, v: str | None) -> str | None:
        if v is not None and not v.strip():
            raise ValueError("Description is required")
        return v.strip() if v is not None else v


class TransactionResponse(BaseModel):
    id: int
    account_id: int
    account_name: str = ""
    category_id: int
    category_name: str = ""
    description: str
    amount: Decimal
    type: Literal["income", "expense"]
    status: Literal["settled", "pending"]
    linked_transaction_id: Optional[int] = None
    recurring_id: Optional[int] = None
    date: datetime.date
    settled_date: datetime.date | None = None
    is_imported: bool = False
    # Track E: True for rows generated by POST /accounts/{id}/adjust-balance.
    # Frontend can use this to render a distinct visual treatment (deferred
    # to a follow-up PR per the architect spec).
    is_manual_adjustment: bool = False

    model_config = {"from_attributes": True}


class BulkDeleteRequest(BaseModel):
    """Body for POST /api/v1/transactions/bulk-delete."""

    model_config = ConfigDict(extra="forbid")

    ids: list[int] = Field(
        ...,
        min_length=1,
        max_length=500,
        description="Transaction IDs to delete. Cross-org IDs are silently ignored. Transfer-pair halves cascade.",
    )


class PromoteToRecurringRequest(BaseModel):
    """Body for POST /api/v1/transactions/{id}/promote-to-recurring.

    Promotes an existing settled-or-pending transaction into a recurring
    template (creates a RecurringTransaction with the tx's account/category/
    amount/type/description and the supplied schedule, then sets
    transaction.recurring_id to the new template).

    Account, category, amount, type, and description come from the source
    transaction. ``auto_settle`` is optional and defaults to False to match
    the standalone recurring-create flow; the create-transaction-with-repeat
    UI passes it through so the user's choice is preserved without needing
    a separate POST /recurring round-trip. Out of scope: promoting transfer
    legs, demoting.
    """

    model_config = ConfigDict(extra="forbid")

    frequency: Literal["weekly", "biweekly", "monthly", "quarterly", "yearly"]
    next_due_date: datetime.date
    auto_settle: bool = False

    @field_validator("next_due_date")
    @classmethod
    def _next_due_date_not_past(cls, v: datetime.date) -> datetime.date:
        # Pydantic-level early reject. Server-side service guard repeats
        # the comparison so date semantics are enforced even if a caller
        # bypasses the schema (e.g. internal reuse).
        if v < datetime.date.today():
            raise ValueError("Date must be today or later")
        return v


class BulkDeleteResponse(BaseModel):
    """Result of a bulk delete."""

    requested_count: int
    deleted_count: int
    skipped_ids: list[int]  # IDs that were requested but not found in this org


class TransactionPairRequest(BaseModel):
    """Op-1 bulk-link / import-confirm-pair / Op-2 pair-with-existing payload."""

    model_config = ConfigDict(extra="forbid")

    expense_id: int
    income_id: int
    transfer_category_id: int | None = None
    recategorize: bool = True


class ConvertToTransferRequest(BaseModel):
    """Op-2 (pair existing) + Op-3 (create missing leg) per-row payload.

    If pair_with_transaction_id is set, the candidate's account_id MUST equal
    destination_account_id (server validates and raises ValidationError on
    mismatch). If unset, the service creates the partner leg on
    destination_account_id.
    """

    model_config = ConfigDict(extra="forbid")

    destination_account_id: int
    pair_with_transaction_id: int | None = None
    transfer_category_id: int | None = None
    recategorize: bool = True


class UnpairTransactionRequest(BaseModel):
    """Op-4 unlink payload. Per-leg fallback categories required because the
    Transfer system category no longer fits once the rows are unlinked.
    """

    model_config = ConfigDict(extra="forbid")

    expense_fallback_category_id: int
    income_fallback_category_id: int


class TransferCandidate(BaseModel):
    """A potential pair candidate returned by GET /transfer-candidates and
    embedded in import preview rows when transfer_match_action requires the
    user to choose.
    """

    id: int
    date: datetime.date
    description: str
    amount: Decimal
    account_id: int
    account_name: str
    date_diff_days: int
    confidence: Literal["same_day", "near_date"]


class TransferCandidatesResponse(BaseModel):
    """Wrapper for GET /api/v1/transactions/{id}/transfer-candidates."""

    candidates: list[TransferCandidate]


class DuplicateCandidate(BaseModel):
    """Embedded in ImportPreviewRow when a CSV row matches an existing linked
    leg on the same account. Lean shape so /import does not refetch row details.

    The synthetic-leg badge keys off existing_leg_is_imported (the matched leg
    itself, not its partner). False means the matched leg was created via Op-3
    convert-and-create or via the manual create-transfer UI.
    """

    id: int
    date: datetime.date
    description: str
    amount: Decimal
    account_id: int
    account_name: str
    existing_leg_is_imported: bool
