export interface User {
  id: number;
  username: string;
  email: string;
  first_name: string | null;
  last_name: string | null;
  phone: string | null;
  avatar_url: string | null;
  email_verified: boolean;
  role: "owner" | "admin" | "member";
  org_id: number;
  org_name: string;
  billing_cycle_day: number;
  is_superadmin: boolean;
  is_active: boolean;
  mfa_enabled: boolean;
  // False for Google SSO users who have not yet set a real password.
  // The Settings UI flips Change Password into "Set a Password" mode and
  // swaps the email-change re-auth from "current password" to a Google
  // step-up flow when this is false.
  password_set: boolean;
  // L3.3 first-run wizard: ISO-8601 timestamp once the user finishes
  // (or skips) onboarding, null otherwise. AppShell uses this to bounce
  // freshly authenticated users to /onboarding. Server-side so the flag
  // survives device changes.
  onboarded_at?: string | null;
  // Track E: org-level toggle controlling whether org admins can call
  // POST /api/v1/accounts/{id}/adjust-balance. Off by default. The
  // accounts page uses this (combined with isAdmin()) to gate the
  // "Adjust balance" button.
  allow_manual_balance_adjustment: boolean;
  subscription_status: SubscriptionStatus | null;
  subscription_plan: string | null;
  trial_end: string | null;
  // Optional platform permissions array. Forward-compat: when /me starts
  // returning effective permissions for non-superadmin platform admins,
  // hasPlatformPermission(user, key) will pick them up without further FE
  // changes. Today the field is undefined, so every gate degrades to the
  // is_superadmin short-circuit (current behavior).
  permissions?: string[];
}

export interface TokenResponse {
  access_token: string;
  token_type: string;
}

export interface MfaChallengeResponse {
  mfa_required: boolean;
  mfa_token: string;
}

export interface MfaSetupResponse {
  qr_code: string;
  secret: string;
  uri: string;
}

export interface MfaEnableResponse {
  recovery_codes: string[];
}

export interface ApiError {
  detail: string;
}

export interface AccountType {
  id: number;
  name: string;
  slug: string | null;
  is_system: boolean;
  account_count: number;
}

export interface Account {
  id: number;
  name: string;
  account_type_id: number;
  account_type_name: string;
  account_type_slug: string | null;
  balance: number;
  currency: string;
  is_active: boolean;
  close_day: number | null;
  is_default: boolean;
  // L3.2 Wave 2A — user-stated starting amount. 0 for accounts that
  // pre-date migration 041; new accounts may set a non-zero value at
  // create time and edit it later. Marked optional on the TS type so
  // existing test fixtures and legacy-shape payloads keep compiling;
  // the runtime API always serializes both fields on AccountResponse.
  opening_balance?: number | string;
  // ISO-8601 yyyy-mm-dd. Set to today on existing rows by the
  // migration; user-editable in the account-edit form.
  opening_balance_date?: string | null;
}

export interface Category {
  id: number;
  name: string;
  type: "income" | "expense" | "both";
  parent_id: number | null;
  parent_name: string | null;
  description: string | null;
  slug: string | null;
  is_system: boolean;
  transaction_count: number;
}

export interface Transaction {
  id: number;
  account_id: number;
  account_name: string;
  category_id: number;
  category_name: string;
  description: string;
  amount: number;
  type: "income" | "expense";
  status: "settled" | "pending";
  linked_transaction_id: number | null;
  recurring_id: number | null;
  date: string;
  settled_date: string | null;
  is_imported: boolean;
  // Track E: True for rows generated by the manual balance adjustment
  // endpoint. Standard CRUD (edit/delete/promote-to-recurring) refuses
  // to mutate them; bulk delete skips them silently.
  is_manual_adjustment: boolean;
}

export interface RecurringTransaction {
  id: number;
  account_id: number;
  account_name: string;
  category_id: number;
  category_name: string;
  description: string;
  amount: number;
  type: "income" | "expense";
  frequency: "weekly" | "biweekly" | "monthly" | "quarterly" | "yearly";
  next_due_date: string;
  auto_settle: boolean;
  is_active: boolean;
}

export interface Budget {
  id: number;
  category_id: number;
  category_name: string;
  amount: number;
  spent: number;
  remaining: number;
  percent_used: number;
  period_start: string;
  period_end: string;
}

export interface BillingPeriod {
  id: number;
  start_date: string;
  end_date: string | null;
}

export interface OrgSetting {
  key: string;
  value: string;
}

export interface ForecastPlanItem {
  id: number;
  plan_id: number;
  category_id: number;
  category_name: string;
  parent_id: number | null;
  type: "income" | "expense";
  planned_amount: number;
  source: "manual" | "recurring" | "history";
  actual_amount: number;
  variance: number;
}

export interface ForecastPlan {
  id: number;
  billing_period_id: number;
  period_start: string;
  period_end: string | null;
  status: "draft" | "active";
  total_planned_income: number;
  total_planned_expense: number;
  total_actual_income: number;
  total_actual_expense: number;
  items: ForecastPlanItem[];
}

// ── Import ──────────────────────────────────────────────────────────────────

export type SuggestionSource = "org_rule" | "shared_dictionary" | "default";

export interface ImportPreviewRow {
  row_number: number;
  date: string;
  description: string;
  amount: number;
  type: "income" | "expense";
  counterparty: string | null;
  transaction_type: string | null;

  // Existing duplicate-detection (different from transfer-leg duplicate)
  is_duplicate: boolean;
  duplicate_transaction_id: number | null;

  // Smart-rules suggestion
  suggested_category_id?: number | null;
  suggestion_source?: SuggestionSource | null;

  // Detector 1: matches an already-linked leg on the same account → drop default
  is_duplicate_of_linked_leg: boolean;
  duplicate_candidate?: DuplicateCandidate | null;
  default_action_drop: boolean;

  // Detector 2: cross-account un-linked match (transfer-pair candidate)
  transfer_match_action: "none" | "pair_with" | "suggest_pair" | "choose_candidate";
  transfer_match_confidence?: "same_day" | "near_date" | "multi_candidate" | null;
  pair_with_transaction_id?: number | null;
  transfer_candidates: TransferCandidate[];
}

export interface ImportPreviewResponse {
  rows: ImportPreviewRow[];
  account_id: number;
  file_name: string;
  total_rows: number;
  duplicate_count: number;

  // New per-spec §3.2 summary counters (replace transfer_candidate_count)
  auto_paired_count: number;
  suggested_pair_count: number;
  multi_candidate_count: number;
  duplicate_of_linked_count: number;
}

export interface ImportConfirmRow {
  row_number: number;
  date: string;
  description: string;
  amount: number;
  type: "income" | "expense";
  category_id: number | null;
  skip: boolean;
  // Spec §3.2 confirm-row action mapping
  action?: "create" | "pair_with_existing" | "drop_as_duplicate" | "create_transfer_pair";
  pair_with_transaction_id?: number | null;
  duplicate_of_transaction_id?: number | null;
  partner_account_id?: number | null;
  transfer_category_id?: number | null;
  recategorize?: boolean;
  // Echoed from preview for accept-vs-override smart-rules detection
  suggested_category_id?: number | null;
  suggestion_source?: SuggestionSource | null;
}

export interface ImportConfirmRequest {
  account_id: number;
  default_category_id: number;
  rows: ImportConfirmRow[];
}

export interface ImportRowError {
  row_number: number;
  error: string;
}

export interface ImportConfirmResponse {
  imported_count: number;
  paired_count: number;
  dropped_duplicate_count: number;
  skipped_count: number;
  error_count: number;
  errors: ImportRowError[];
}

// L3.2 Wave 2A manual batch transaction entry. Wraps a TransactionCreate
// payload with a stable row_number for per-row outcome mapping.
export interface BatchTransactionRowInput {
  row_number: number;
  transaction: {
    account_id: number;
    category_id: number;
    description: string;
    amount: string;
    type: "income" | "expense";
    date: string;
    status?: "settled" | "pending";
    settled_date?: string | null;
  };
}

export interface BatchTransactionsRequestBody {
  rows: BatchTransactionRowInput[];
}

export interface BatchRowResult {
  row_number: number;
  transaction_id: number;
}

export interface BatchRowError {
  row_number: number;
  error: string;
}

export interface BatchTransactionsResponse {
  imported_count: number;
  error_count: number;
  results: BatchRowResult[];
  errors: BatchRowError[];
}

export interface Plan {
  id: number;
  name: string;
  slug: string;
  description: string;
  is_custom: boolean;
  is_active: boolean;
  sort_order: number;
  price_monthly: number;
  price_yearly: number;
  max_users: number | null;
  retention_days: number | null;
  features: PlanFeatures;
}

export type SubscriptionStatus = "trialing" | "active" | "past_due" | "canceled";

export interface SubscriptionDetail {
  id: number;
  org_id: number;
  plan: Plan;
  status: SubscriptionStatus;
  billing_interval: "monthly" | "yearly";
  trial_start: string | null;
  trial_end: string | null;
  current_period_start: string | null;
  current_period_end: string | null;
}

// L4.11 feature entitlements -------------------------------------------------

export type FeatureKey =
  | "ai.budget"
  | "ai.forecast"
  | "ai.smart_plan"
  | "ai.autocategorize";

export interface PlanFeatures {
  "ai.budget": boolean;
  "ai.forecast": boolean;
  "ai.smart_plan": boolean;
  "ai.autocategorize": boolean;
}

export interface OrgFeatureOverride {
  feature_key: FeatureKey;
  value: boolean;
  set_by: number | null;
  set_by_email: string | null;
  set_at: string;          // ISO 8601 UTC
  expires_at: string | null;  // ISO 8601 UTC
  note: string | null;
  is_expired: boolean;
}

export interface FeatureStateRow {
  key: FeatureKey;
  plan_default: boolean;
  effective: boolean;
  override: OrgFeatureOverride | null;
}

export interface FeatureStateResponse {
  plan: { id: number; name: string; slug: string } | null;
  features: FeatureStateRow[];
}

// ── Transfer-pair shapes ─────────────────────────────────────────────────────

export interface TransferCandidate {
  id: number;
  date: string;
  description: string;
  amount: number;
  account_id: number;
  account_name: string;
  date_diff_days: number;
  confidence: "same_day" | "near_date";
}

export interface TransferCandidatesResponse {
  candidates: TransferCandidate[];
}

export interface DuplicateCandidate {
  id: number;
  date: string;
  description: string;
  amount: number;
  account_id: number;
  account_name: string;
  existing_leg_is_imported: boolean;
}

export interface TransactionPairRequest {
  expense_id: number;
  income_id: number;
  transfer_category_id?: number | null;
  recategorize?: boolean;
}

export interface ConvertToTransferRequest {
  destination_account_id: number;
  pair_with_transaction_id?: number | null;
  transfer_category_id?: number | null;
  recategorize?: boolean;
}

export interface UnpairTransactionRequest {
  expense_fallback_category_id: number;
  income_fallback_category_id: number;
}

export interface AuditEvent {
  id: number;
  event_type: string;
  actor_user_id: number | null;
  actor_email: string;
  target_org_id: number | null;
  target_org_name: string | null;
  request_id: string | null;
  ip_address: string | null;
  outcome: "success" | "failure";
  detail: Record<string, unknown> | null;
  created_at: string;
}

export interface AuditEventListResponse {
  items: AuditEvent[];
  total: number;
}

// L4.8 — Role administration UI.

export interface RoleListItem {
  id: number;
  slug: string;
  name: string;
  description: string | null;
  is_system_frozen: boolean;
  permission_count: number;
  created_at: string;
  updated_at: string;
}

export interface RoleListResponse {
  items: RoleListItem[];
}

export interface RoleDetail {
  id: number;
  slug: string;
  name: string;
  description: string | null;
  is_system_frozen: boolean;
  permissions: string[];
  created_at: string;
  updated_at: string;
}

export interface RoleCreatePayload {
  slug: string;
  name: string;
  description?: string | null;
  permissions: string[];
}

export interface RoleUpdatePayload {
  name?: string;
  description?: string | null;
  permissions?: string[];
}

export interface PermissionCatalogResponse {
  namespaces: Record<string, string[]>;
  keys: string[];
}

// L4.6 — System usage analytics (counts-only first slice).

export interface DailyCount {
  date: string; // ISO date (YYYY-MM-DD).
  count: number;
}

export interface OrgTxVolume {
  rank: number;
  org_id: number;
  org_name: string;
  tx_count: number;
}

export interface DormantOrg {
  org_id: number;
  org_name: string;
  last_tx_at: string | null;
  days_since_last_activity: number | null;
}

export interface AnalyticsResponse {
  window_days: number;
  generated_at: string;
  logins_by_day: DailyCount[];
  tx_writes_by_day: DailyCount[];
  imports_by_day: DailyCount[];
  top_orgs_by_tx_volume: OrgTxVolume[];
  dormant_orgs: DormantOrg[];
}
